# Generated by Django 3.1 on 2021-08-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftboard',
            name='date',
            field=models.DateField(),
        ),
    ]
