# Generated by Django 3.1 on 2021-08-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0002_auto_20210807_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftboard',
            name='test',
            field=models.IntegerField(choices=[(1, 'test'), (2, 'mamushi')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiftboard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='shift.category', verbose_name='カテゴリ'),
        ),
    ]
