# Generated by Django 3.1 on 2021-08-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0004_remove_shiftboard_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftboard',
            name='test',
            field=models.CharField(choices=[('te', 'mamushi'), ('te', 'mamushi')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
