# Generated by Django 3.1 on 2021-08-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0005_shiftboard_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftboard',
            name='test',
        ),
        migrations.AlterField(
            model_name='shiftboard',
            name='category',
            field=models.CharField(choices=[('施工', '施工'), ('コンサル', 'コンサル'), ('記念日', '記念日')], max_length=10),
        ),
    ]
