# Generated by Django 3.1 on 2021-08-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0006_auto_20210810_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftboard',
            name='release',
            field=models.BooleanField(default=False, verbose_name='公開中'),
        ),
        migrations.AlterField(
            model_name='shiftboard',
            name='category',
            field=models.CharField(choices=[('施工', '施工'), ('コンサル', 'コンサル'), ('記念日', '記念日')], max_length=10, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='shiftboard',
            name='date',
            field=models.DateField(verbose_name='日程'),
        ),
    ]
